home_dir := env_var('HOME')
bin := home_dir + "/vpic-kokkos/build/bin/vpic"

default: q-info
  @just --list

h2d_wind:
	{{bin}} low2high_2d_alfven_wind.cxx

q-submit:
    qsub -V job.hvpic.mpi.2d.alfven.wind.derecho.pbs

q-info:
    qhist -u $USER
    qstat -u $USER