project:
  type: website
  preview: 
    port: 4224

website:
  sidebar:
    contents: auto
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true

bibliography:
  - ../share/bibliography/research.bib