name: warpx
channels:
  - conda-forge
dependencies:
  - python<3.12
  - jupyter
  - papermill
  
  - rich
  - loguru
  - icecream
  
  - jupyter_bokeh # VSCode support

  - fastcore
  - pydantic

  - plasmapy
  - dill

  - yt

  - panel
  - hvplot

  - pyarrow
  - polars

  # VisualPIC
  - pyqt

  - pip
  - pip:
    - ../space_analysis
    - git+https://github.com/AngelFP/VisualPIC.git@dev
    - git+https://bitbucket.org/ecp_warpx/picviewer/
    # - mpi4py
    # - h5py
    # - openpmd-api