name: warpx
channels:
  - conda-forge
dependencies:
  - python<3.12
  - jupyter
  - papermill
  
  - rich
  - loguru
  - icecream

  - beartype<0.18
  
  - jupyter_bokeh # VSCode support

  - fastcore
  - pydantic

  - plasmapy
  - dill

  - yt

  - panel
  - hvplot

  - pyarrow
  - polars

  # VisualPIC
  - pyqt

  - pip
  - pip:
    - ../space_analysis
    # - mpi4py
    # - h5py
    # - openpmd-api