name: warpx
channels:
  - conda-forge
dependencies:
  - python<3.12
  - jupyter
  - jupyter_bokeh
  - fastcore
  - pydantic

  - plasmapy
  - dill

  - yt

  - pip
  - pip:
    - mpi4py
    - h5py
    - openpmd-api