---
title: Hybrid Simulation of Alfven Wave and Rotational Discontinuities
draft: true
code-links:
  - text: Zotero
    href: zotero://select/library/collections/STTJNMAQ/
---

::: {.callout-note}
Note that this is a work in progress. The content is subject to change and the website is not well organized.
:::

$$
P_{parp} = |P_{xx} \cdot B_x + P_{yy} \cdot B_y + P_{zz} \cdot B_z| / |B|
$$

- Compare $ \delta v_A ?= \delta v_i $ first
- One step back, how the RD evolve after generation?
- Velocity distribution function
- @omidiRotationalDiscontinuitiesAnisotropic1992 [Zotero](zotero://select/items/1_A8E2L5T7)
  - Title:: Rotational discontinuities in anisotropic plasmas 
- @vasquezNonlinearEvolutionAlfven1999
  - Title:: Nonlinear evolution of Alfvén waves and RDs-hybrid simulations

### BUGS

- [x] beta and ion temperature


# TODO:

- [ ] Ion anisotropy depends on electron beta
- [ ] Dimension difference when go to 2D/3D
- [ ] Check ion gyro-radius
- [ ] Propagation direction (ion or electron sense RD)
- [ ] Why constant B? (Marco Velli)



---

Ion dynamics in the rotational discontinuities

Formation of rotational discontinuities from oblique linearly polarized Alfven wave trains
And ion dynamics in the vicinity of the rotational discontinuities => Hybrid Simulation


> Generally speaking the hybrid model approach has difficulty with Whistler waves that are included in the model physics but because their dispersion runs to the electron cyclotron frequency there is a point where the chosen grid and timestep resolution no longer properly resolves these waves (unless you use a very small timestep in which case the value of the hybrid approach is lost).

Numerical dispersion by whistler waves (up to electron cyclotron frequency)


The ponderomotive force (o(OB~l~/Ox) exerted by the first-order wave generates waves with twice its wavenumber which have a compressional component and a wave magnetic field in the z-direction.