[project]
name = "warpx"
version = "0.1.0"
description = "Add a short description here"
authors = ["Beforerr <zzj956959688@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
jupyter = "*"
warpx = "*"

[pypi-dependencies]
beforerr = { path = "../beforerr_dev", editable = true}
space_analysis = { path = "../space-analysis.py", editable = true}

[target.osx-arm64.dependencies]
python = "<3.12"
ccache = "*"
cmake = "*"
llvm-openmp = "*"
ninja = "*"
blaspp = "*"
lapackpp = "*"
pkg-config = "*"
openmpi = "*"
fftw = { version = "*", build = "mpi_openmpi*" }
h5py = { version = "*", build = "mpi_openmpi*" }
