default:
    python main.py --help
    julia main.jl --help

plot:
    python main.py --plot-wk-spectrum --export
    python main.py --eta 10 --plot-wk-spectrum --export
    julia main.jl run --eta 10

log-v1:
    directory

log-v0:
    python main.py --beta 0.25 --eta 10 
    julia main.jl run --beta 0.25 --eta 10

    python main.py --beta 2 --eta 10 --plot-plasma-velocity
    julia main.jl run --beta 2 --eta 10

    python main.py --theta 0 --beta 0.25 --eta 100 --plot-plasma-velocity
    julia main.jl run --theta 0 --beta 0.25 --eta 100

    python main.py --theta 0 --beta 2 --eta 200  --plot-plasma-velocity
    julia main.jl run --theta 0 --beta 2 --eta 200

    python main.py --theta 0 --beta 0.25 --eta 200
    julia main.jl run --theta 0 --beta 0.25 --eta 200
