default:
    python main.py --help

run:
    python main.py

log:
    python main.py
    python main.py --plasma-resistivity 10 --nppc 256 --substeps 32
    python main.py --beta 2 --plasma-resistivity 10