default:
    python main.py --help

run:
    python main.py

log:
    python main.py
    python main.py --eta 10 --nppc 256 --substeps 32
    python main.py --beta 2 --eta 10 --nppc 256 --substeps 32
    python main.py --theta 0 --beta 0.25 --eta 200  --nppc 256 --substeps 32 --time-norm 1000
    python main.py --theta 0 --beta 2 --eta 200  --nppc 256 --substeps 32

    python main.py --lz-norm 32 --dz-norm 0.25