default:
    python main.py --help
    julia main.jl --help

plot:
    python main.py --plot-wk-spectrum --export
    python main.py --eta 10 --plot-wk-spectrum --export
    julia main.jl run --eta 10

run directory:
    python main.py --directory {{directory}}
    julia main.jl run --directory {{directory}}

log-sim:
    python run.py print_config --help

    # python main.py
    # python main.py --eta 10 --nppc 256 --substeps 32
    # python main.py --beta 2 --eta 10 --nppc 256 --substeps 32
    # python main.py --theta 0 --beta 0.25 --eta 200  --nppc 256 --substeps 32 --time-norm 1000
    # python main.py --theta 0 --beta 2 --eta 200  --nppc 256 --substeps 32
    # python main.py --lz-norm 32 --dz-norm 0.25


log-v1:
    just run "01_oblique_linear_alfven/dim_1_beta_0.25_theta_0.0_eta_100.0"
    just run "01_oblique_linear_alfven/dim_1_beta_2.0_theta_0.0_eta_200.0"
    just run "01_oblique_linear_alfven/dim_1_beta_0.25_theta_60.0_eta_100.0_l_64.0"
    just run "01_oblique_linear_alfven/dim_1_beta_0.25_theta_60.0_eta_100.0_l_32.0"
    just run "01_oblique_linear_alfven/dim_1_beta_2.0_theta_60.0_eta_10.0_l_64.0"

log-v0:
    python main.py --beta 0.25 --eta 10 
    julia main.jl run --beta 0.25 --eta 10

    python main.py --beta 2 --eta 10 --plot-plasma-velocity
    julia main.jl run --beta 2 --eta 10

    python main.py --theta 0 --beta 0.25 --eta 100 --plot-plasma-velocity
    julia main.jl run --theta 0 --beta 0.25 --eta 100

    python main.py --theta 0 --beta 2 --eta 200  --plot-plasma-velocity
    julia main.jl run --theta 0 --beta 2 --eta 200

    python main.py --theta 0 --beta 0.25 --eta 200
    julia main.jl run --theta 0 --beta 0.25 --eta 200
